#!/bin/bash

if [ ! -f /home/user/.config/koreader/settings.reader.lua ]; then
    mkdir -p /home/user/.config/koreader
    cp /opt/settings.reader.lua /home/user/.config/koreader/settings.reader.lua
fi
sleep 10
exec /usr/bin/koreader
